### ISSUE TITLE
Delegation-related errors with 0.2.4 and 0.2.5

### ISSUE THREAD

**Issue by mjgiarlo** [trailblazer/reform-rails#101]
The 0.2.5 release fixed the `ArgumentError` I wrote up in #99, but I'm now seeing odd behavior in an app that uses reform-rails (and I see the error when `Reform::Form::ActiveModel.included` does delegation via `delegate` or `def_delegators` but **not** when it uses `Uber::Delegates`).

More about my app:
* [form](https://github.com/sul-dlss/argo/blob/main/app/forms/tags_form.rb#L3-L19)
* [instantiation of form](https://github.com/sul-dlss/argo/blob/main/app/controllers/tags_controller.rb#L62) (you can ignore the `ModelProxy` hijinks for now, as I am seeing the same error even when I ditch the `ModelProxy` which may be cruft)
* [the test that now fails](https://github.com/sul-dlss/argo/blob/main/spec/requests/tags_spec.rb#L82-L92)

I tossed a debugger in the form to sniff at the value of `tags` which comes through the form's populator, and here's a difference that seems relevant:

```
# With 0.2.4 and 0.2.5
(byebug) tags.first.id
"Some : Thing" # this is surprising, and the cause of the failing test
(byebug) tags.first.method(:id)
#<Method: #<Class:0x00007f88bef324f8>#id(...) /media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.2.2@argo/gems/reform-rails-0.2.5/lib/reform/form/active_model.rb:9>

# With 0.2.3
(byebug) tags.first.id
""
(byebug) tags.first.method(:id)
#<Method: #<Class:0x00007f912389ae70>(#<Module:0x00007f9123899b10>)#id() /media/mjg/44aee93d-a48a-4ad3-ae90-4b084bb04b69/rvm/gems/ruby-3.2.2@argo/gems/disposable-0.6.3/lib/disposable/twin.rb:72>
```

So, naïvely, this seems related to how id delegation is being handled?

**Comment by apotonick** [comment]
May I ask where the `"Some : Thing"` value is coming from? Is that actually set on the form?

**Comment by mjgiarlo** [comment]
@apotonick 💬 
> May I ask where the `"Some : Thing"` value is coming from? Is that actually set on the form?

Sure, the `"Some : Thing"` value is one of the tags that is currently persisted and injected into the form at instantiation time. You can see that happening here: https://github.com/sul-dlss/argo/blob/main/app/controllers/tags_controller.rb#L60-L62 (The value of `current_tags` is an array with one member that responds to `:name` and returns `"Some : Thing"`.)

**Comment by mjgiarlo** [comment]
I'll add that this is with Ruby 3.2.2 and Rails 7.0.4.3.

**Comment by apotonick** [comment]
So, in other words, `form.id` returns `form.name`?

**Comment by mjgiarlo** [comment]
@apotonick 💬 
> So, in other words, `form.id` returns `form.name`?

It's not the ID of the form itself that is mistakenly returning a name; it's the ID of the  value within the `Disposable::Twin::Collection` that comes out of the form's populator. The delegation change in `lib/reform/form/active_model.rb` is what changed the behavior, as best I can tell.

**Comment by apotonick** [comment]
The "value" within the collection still is a `Form` instance  unless you tell me it's not? `item = form.tags[0]` should be a form, and `item.id` should not return `name`. If you can, come meet me here https://trailblazer.zulipchat.com

**Comment by mjgiarlo** [comment]
I threw [a patch](https://github.com/sul-dlss/argo/pull/4024/commits/62e22a6b757a967ccec63ab7736c0f249cf7bf79) at this form's populator and now the associated spec passes with both reform-rails 0.2.3 and 0.2.5. I'm currently not convinced the delegation change in reform-rails was a bug, but let me noodle on this a bit more to better grok how what we had before used to function before I close this issue.

**Comment by apotonick** [comment]
Regardless of your _noodling_ I will add your populator as an example what to improve in Reform 3... :beer:

**Comment by mjgiarlo** [comment]
🍻

**Comment by mjgiarlo** [comment]
I paired with a colleague who worked on this code earlier, and neither of us could remember why we configured this populator the way we did or even make much sense of how it had been working. We did conclude that between the populator and our janky model proxy approach... the delegation change in reform-rails is not a bug after all. Thanks again for engaging on this. Closing!

**Comment by apotonick** [comment]
:sweat_smile: Great to hear it's working, again, Michael!

One more question: as it seems you guys are pretty heavily using Reform (correct me if I'm assuming the wrong here), would it be possible to consult with you regarding problems/requests you might have for Reform 3?
