### ISSUE TITLE
validates_uniqueness_of doesn't work in validation groups

### ISSUE THREAD

**Issue by RKushnir** [trailblazer/reform-rails#16]
Basically, it's only implemented as a method on the form itself, but not on the validation group.
So the following works:
```ruby
class MyForm < Reform::Form
  validates_uniqueness_of :foo
end
```
and this doesn't:
```ruby
class MyForm < Reform::Form
  validation :bar do
    validates_uniqueness_of :foo
  end
end
```

To make it clear, this is not a feature request, it's a shortcoming in the existing API.

**Comment by fran-worley** [comment]
As per the trailblazer [guide](http://trailblazer.to/gems/reform/validation.html#uniqueness-validation) you should be careful using the native active model uniqueness validation. 

We won't be adding enhanced support for this as we are trying to encourage people to use the reform unique validation:

```ruby
validation :bar do
  validates :foo, unique: true
end
```

**Comment by RKushnir** [comment]
Thanks, @fran-worley I must have missed the moment it was introduced.
