### ISSUE TITLE
`uninitialized constant Reform::Form::ActiveModel::ActiveModel` in Rails 5 with dry

### ISSUE THREAD

**Issue by tap349** [trailblazer/reform-rails#20]
Good day! I use Rails 5, reform-rails 0.1.5, dry-validation 0.9.5.

When setting validation engine to `dry-validation` in initializer:

``` ruby
Rails.application.config.reform.validations = :dry
```

loading fails:

```
/Users/tap/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-rails-0.1.5/lib/reform/form/active_model.rb:7:in `block in included': uninitialized constant Reform::Form::ActiveModel::ActiveModel (NameError)
    from /Users/tap/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-rails-0.1.5/lib/reform/form/active_model.rb:5:in `class_eval'
    from /Users/tap/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-rails-0.1.5/lib/reform/form/active_model.rb:5:in `included'
    from /Users/tap/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-rails-0.1.5/lib/reform/rails/railtie.rb:49:in `include'
    from /Users/tap/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-rails-0.1.5/lib/reform/rails/railtie.rb:49:in `block in dry!'
    from /Users/tap/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-rails-0.1.5/lib/reform/rails/railtie.rb:48:in `class_eval'
    from /Users/tap/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-rails-0.1.5/lib/reform/rails/railtie.rb:48:in `dry!'
    from /Users/tap/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reform-rails-0.1.5/lib/reform/rails/railtie.rb:12:in `block in <class:Railtie>'
...
```

I have figured it out that it's also necessary to require `'reform/form/active_model/validations'` (in addition to `'reform/form/active_model'`):

``` ruby
require 'reform/form/active_model/validations'

Rails.application.config.reform.validations = :dry
```

(or somewhere after this line: https://github.com/trailblazer/reform-rails/blob/master/lib/reform/rails/railtie.rb#L46)

this way it works.
IDK if it matters but I have also disabled AR in my `application.rb` (using rom-rb - yeah, a strange combo :) ):

``` ruby
# require 'active_record/railtie'
```

**Comment by apotonick** [comment]
Hm, weird, ActiveModel shouldn't be loaded at all...

**Comment by tap349** [comment]
in case anyone would like to debug it here are the steps to reproduce the error:

1) generate new Rails 5 project:

$ rails new rails_test --skip-active-record

2) add gems to `Gemfile`:

```ruby
gem 'dry-validation'
gem 'reform'
gem 'reform-rails'
```

run `bundle install`

3) configure to use dry validation engine in `config/initializers/reform.rb`:

```ruby
Rails.application.config.reform.validations = :dry
```

4) comment out requiring "active_model/railtie" in `config/application.rb`:

```ruby
#require "active_model/railtie"
```

comment out this line causes error when launching rails console:

```
$ rails console

0.1.5/lib/reform/form/active_model.rb:7:in `block in included': uninitialized constant Reform::Form::ActiveModel::ActiveModel (NameError)
...
```

**Comment by apotonick** [comment]
The problem is here: https://github.com/trailblazer/reform-rails/blob/master/lib/reform/rails/railtie.rb#L46

I decided to include this so gems like SimpleForm etc. still work and people don't send me "bug" reports every five minutes that their form helpers don't work anymore. 

You can add another option `reform.disable_active_model = false` to prevent this from happening. Do you want to do that? :beers:

**Comment by apotonick** [comment]
BTW thanks for your reproduction list, helped me to save brain and time!

**Comment by tap349** [comment]
@apotonick sorry for late answer. adding this option would be great - it looks much better than some magical `require` in initializer :)

P.S. this option didn't get into the last release?

**Comment by fran-worley** [comment]
@tap349 I've just added this into master via https://github.com/trailblazer/reform-rails/commit/85484f75da7695c0410cf055e016458f8f263d56 .

Can you try it out for me so I include it in the next release?

**Comment by tap349** [comment]
@fran-worley thanks, it works ) 

BTW in this commit I see that `enable_active_model_builder_methods` option is `false` by default. this is perfectly fine for me since I don't use ActiveModel but probably the opposite case is more common - that is when people do use ActiveModel. Thus maybe it makes sense to set it `true` by default (or change the name to `disable_active_model_builder_methods` and leave default value as is)?

**Comment by fran-worley** [comment]
@tap349 if you use ActiveModel validation those methods are included regardless of how you set that config var. It only applies if you use dry hense why I've set the default to false

**Comment by tap349** [comment]
@fran-worley I've just encountered an error when trying to validate nested params using master branch and dry backend with `enable_active_model_builder_methods = false`:

```
undefined method `keys' for ["amount", "1"]:Array
```

params hash:

```
{"name"=>"name", "budgets"=>{"amount"=>"1"}}
```

previously nested param key had postfix `_attributes`:

```
{"name"=>"name", "budgets_attributes"=>{"amount"=>"1"}}
```

**Comment by fran-worley** [comment]
That'll be because rails form_helpers change the param when you use ':fields_for' to append the '_attributes'. In disabling all of the rails form magic the code that converts it back will no longer be included.

**Comment by tap349** [comment]
@fran-worley Can you please clarify it a little bit for me? I use SimpleForm and `simple_fields_for` (that might use rails form helpers internally) but since I don't include AM builder methods (`enable_active_model_builder_methods = false`) I get nested param keys without `_attributes` prefix. But why do I have the error above when validating reform form?
