### ISSUE TITLE
unique validator - persisted record allow count issue

### ISSUE THREAD

**Issue by ridget** [trailblazer/reform-rails#24]
I have an existing record a, with a name attr on the model of 'foo' and a persisted record being validated, b, and b's name is being changed to 'foo'.

When i run the validation against b, the unique validation passes, because it is persisted, the allow count is set to 1, and the query count is also 1.

Should not the allow count be set to 1, only if b is included in the query?

Have patched this locally, so happy to supply a PR just wanted to confirm this case first.

**Comment by adisos** [comment]
https://github.com/trailblazer/reform-rails/pull/21 related

**Comment by ridget** [comment]
@adisos #21 solves the bug. Ill close this off in lieu of your PR if you don't mind?
