### ISSUE TITLE
Bug in uniqueness validation

### ISSUE THREAD

**Issue by ujh** [trailblazer/reform-rails#25]
This is essentially https://github.com/apotonick/reform/pull/333, i.e. when renaming a unique attribute to a value of another existing entry in the DB that this is not caught using the existing code.

I'd love to write a test case for this but I can't even get the current test suite to pass. `rake` gives me a lot of error messages (I've checked out `v2.2.1` of reform and `master` is even worse as it produces a segfault). Is there something special I need to do to get this to work?

See [errors.txt](https://github.com/trailblazer/reform-rails/files/482194/errors.txt) for the full output of running `rake` in the top level directory of `reform-rails` with Ruby 2.3.1.

**Comment by alessandro1997** [comment]
👍 this is only happening with reform-rails 0.1.6. 0.1.5 works fine. Oddly enough, there doesn't seem to be a tag for 0.1.6 here on GitHub.

**Comment by fran-worley** [comment]
@alessandro1997 we've just pulled reform-rails v0.1.6. 
@ujh you should be able to get the suite to pass now (though not with rails 5) 

Can you check the changes made via this PR https://github.com/trailblazer/reform-rails/pull/21 as it looks like the second part of this might fix your issue.

**Comment by ujh** [comment]
Yes, #21 should fix the issue. 👍

**Comment by alessandro1997** [comment]
Great! 👍
