### ISSUE TITLE
Undefined method persisted? with json field

### ISSUE THREAD

**Issue by Vaultman** [trailblazer/reform-rails#26]
I'm trying to use postgres JSONB fields using Hash as described in your [blogpost](https://apotonick.wordpress.com/2016/07/06/schemaless-models-with-hash-fields-or-jsonb/). 
I'm getting `undefined method persisted? for {}:Hash` when I try to display json fields using simple_form (and simple_fields_for or fields_for). I have this exact issue even with your example from your blogpost. 
Reform version is 2.2.1, reform-rails 0.1.5, disposable 0.3.2 and Rails version is 4.2.7.

**Comment by apotonick** [comment]
Ah, that must be because simple form thinks the nested hash is a model. Can you tell `fields_for` to skip this magic guess?

**Comment by Vaultman** [comment]
Oh, when I use `f.simple_fields_for @form.slack do |s|` instead of a `f.simple_fields_for :slack do |s|` it seems to work just fine.

**Comment by fran-worley** [comment]
@Vaultman I think the cleanest thing to do is just to update the docs to make people aware of this little gotcha when using rails form builders.

We won't be putting any more time in to improved integration with rails form builders like SimpleForm, but if you've got ideas PRs are always welcome 😸
