### ISSUE TITLE
Rails 5 - Acceptance validation error

### ISSUE THREAD

**Issue by fran-worley** [trailblazer/reform-rails#30]
This [commit](https://github.com/rails/rails/commit/37661bfc810da7384ac6650d60be8669baa16813#diff-4bd768938162ea6ee67ebb1ef7f9332c) to the rails acceptance validation causes a stack level too deep error when trying to use it in reform.

[Tests](https://github.com/trailblazer/reform-rails/blob/master/test/activemodel_validation_test.rb#L242-L256) skipped for now.

**Comment by alessandro1997** [comment]
@fran-worley do you know of any workarounds or potential fixes? I am using `acceptance` in my Rails app and had to disable it because I upgraded to Rails 5.

**Comment by fran-worley** [comment]
Use an alternative validation library like dry-validation??

You could also just implement it manually by adding in your virtual attribute and checking that it's value is equal to whatever you deem to be acceptance.

Given that I'm not currently using Rails 5 or ActiveModel validations this isn't going to be very high on my list of things to fix.

PRs are always appreciated though 😉

**Comment by alessandro1997** [comment]
I am using dry-validation in another project, so yes, it might be time to switch here as well. 😄 

Thanks for the advice!
