### ISSUE TITLE
Compability with active_model-errors_details gem

### ISSUE THREAD

**Issue by adisos** [trailblazer/reform-rails#33]
https://github.com/cowbell/active_model-errors_details - Adds ActiveModel::Errors#details to return type of used validator - Backport from Rails 5.0

**Comment by apotonick** [comment]
What's the difference to `errors[:name]`, for example?

BTW we introduce a new errors API in Reform 2.3, so your issue came in at the perfect time! :+1:

**Comment by coatezy** [comment]
I have also noticed that error details are not being set when using Rails 5. I am guessing this is  because the current errors API in Reform does not expose this information?

If I add a custom error with a matching i18n locale

`errors.add(:design, :not_in_use)`

 I get back the error message and detail.

```
@details={:design=>[{:error=>:not_in_use}]},
@messages={:design=>["not in use"]}
```

But the default active record validation errors do not.

```
@details={:description=>[{:error=>"can't be blank"}]},
@messages={:description=>["can't be blank"]}
```

**Comment by apotonick** [comment]
Thanks @coatezy - the reason is until today I didn't even know the concept of "detail" now exists for AM errors.

**Comment by coatezy** [comment]
No problem @apotonick! Just thought I'd add a little more info to the issue so it is clear what is working/not working. 😄 👍

**Comment by apotonick** [comment]
Yeah that's great, the more you describe the better @fran-worley and I can work out the new `Errors` API for Reform 2.3! :beers:

**Comment by coatezy** [comment]
I am currently implementing an API and use the details hash to return the error type when rendering errors. I have monkey patched for now but it would be nice if Reform Rails could support details.

Pretty sure `#details` was introduced in Rails 5 so it would need to use this approach if Rails 5 is being used and fall back to the old approach if Rails 4 or less is being used.

https://github.com/trailblazer/reform-rails/blob/master/lib/reform/form/active_model/validations.rb#L55

```ruby
def call(fields, errors, form)
    validator = @validations.new(form)
    validator.valid?

    validator.errors.details.each do |name, error_options|
      error_options.each do |option|
        error = option.delete(:error)
        errors.add(name, error, **option)
      end
    end
  end
```

Hope this help someone though if you need `#details` now.

**Comment by fran-worley** [comment]
@coatezy we now (on master) delegate `errors.add()` to ActiveModel rather than using our own implementation so this shouldn't be a problem anymore.

**Comment by coatezy** [comment]
Cool! I'll check out master. Thanks @fran-worley!

**Comment by fran-worley** [comment]
@coatezy no worries, just make sure that you're also using reform from master or it won't run!

**Comment by dnd** [comment]
@fran-worley I just tried upgrading my reform, and reform-rails to point to master. I am finding that while directly validating on a model contains an `errors` object that exposes `details` and `messages`, validating on a reform object does not expose the `details` at all.

This is what pry shows for the object:
```
[6] pry(#<Grape::Middleware::Error>)> ls form.errors                                                                                                                                      
Reform::Contract::Result::Errors#methods: full_messages  messages  size
Reform::Form::ActiveModel::Validations::Result::ResultErrors#methods: []  empty?  to_s
instance variables: @dotted_errors  @form  @result  @success
```

Are there any tests around this functionality? If so I'll pull down reform-rails locally and try to run them to make sure it's not something stupid with my app

**Comment by fran-worley** [comment]
@dnd Nope, it's not your app we weren't delegating the result errors object.
You should be sorted now with https://github.com/trailblazer/reform-rails/commit/bd0ddef1ebbb975eb4efc46933b4291f58f3e79d .

**Comment by dnd** [comment]
I got everything updated, and it's working perfectly now. Thanks for the quick turnaround!
