### ISSUE TITLE
Question: Are nested forms saved in a transaction?

### ISSUE THREAD

**Issue by mcmire** [trailblazer/reform-rails#37]
I've used Reform for a few times and every time I start to use nested forms, I stop and ask the question, are nested forms saved in a transaction? My guess would be that they are not, since Reform doesn't know anything about ActiveRecord or any ORM for that matter. I've looked in this gem, and I haven't found anything related to that. I've also looked in Disposable, too, and found [this bit of code](https://github.com/apotonick/disposable/blob/master/lib/disposable/twin/save.rb#L18) which saves nested twins. Is this assumption correct?

**Comment by apotonick** [comment]
Correct, `Reform` simply calls `save` on the "models". You can do it manually and wrap whatever you need into transactions. Need an example?

**Comment by mcmire** [comment]
@apotonick Well, I think what's worked for me so far is to let Rails take care of it:

``` ruby
class PostForm < Reform::Form
  collection :comments, form: Comment

  def sync
    super

    comments.each do |comment|
      model.comments << comment.model
    end
  end

  def save
    sync
    model.save
  end

  # This ends up being pretty useful too
  def save!
    sync
    model.save!
  end
end
```

I don't know if this is standard practice or what, though. (It feels a little dirty too.)

Regardless, I think it would be nice to have something in the docs about this. Because I think people are going to come from ActiveRecord and think, "oh, if I add a `collection` then Reform will just take care of everything for me!" and be pleasantly surprised to find that nothing fancy happens here.

**Comment by apotonick** [comment]
This does actually not look right, since Disposable will take care of what you do manually. Besides that, this kind of code is supposed to be written in the Trailblazer operation and not the form object.

Can you make a small example where you show me what initial object state, input, and desired side effect you want?
