### ISSUE TITLE
Validating collection presence with dry-validation does not consider rails '_attributes' params

### ISSUE THREAD

**Issue by kofronpi** [trailblazer/reform-rails#42]
When using dry-validation as the validation engine, let's say I have this validation block in my form:
```
collection :members # ...
# ...
  validation do
    required(:members).filled
  end
```

Validating the form with a valid `members_attributes` subhash fails, the form is marked as invalid and the validation error triggered.

**Comment by fran-worley** [comment]
@kofronpi if you're using rails form builders they will add the _attributes and do some other craziness to the format of your nested params. 

You'll need to include (as a minimum)

https://github.com/trailblazer/reform-rails/blob/master/lib/reform/form/active_model/form_builder_methods.rb

to transform the rails style params into something that dry will be able to interpret. We should probably add something in the docs to explain this....

**Comment by th1988** [comment]
Hey guys 
I've added a note to the docs https://github.com/trailblazer/trailblazer.github.io/pull/98
