### ISSUE TITLE
Call private method `property` when include Disposable::Twin::Parent

### ISSUE THREAD

**Issue by bootleq** [trailblazer/reform-rails#45]
Hi, I'm using Reform with ActiveModel.
When trying to include `Disposable::Twin::Parent` it reports `private method 'property' called` error.

Code example:
```ruby
class Form < Reform::Form
  feature Disposable::Twin::Parent
end
```

I found the reason could be `Reform::Form::ActiveModel` defines `property` as private method, at [form_builder_methods.rb#L14-L18][].
And `Parent` will try add a `parent` property by calling `property` ([parent.rb#L3])

Not sure how to handle it, maybe move the method to public? as it's public in `Reform::Form` itself.

[form_builder_methods.rb#L14-L18]: https://github.com/trailblazer/reform-rails/blob/50bdf9f3792eb931142081cc129d32a4adb50142/lib/reform/form/active_model/form_builder_methods.rb#L14-L18
[parent.rb#L3]: https://github.com/apotonick/disposable/blob/6305c7b4b5b7cb0f364587bac01df7bc3c866246/lib/disposable/twin/parent.rb#L3

**Comment by apotonick** [comment]
This is fixed with the latest `disposable`. :wink:
