### ISSUE TITLE
Integration simple_for and reform 2.3.0

### ISSUE THREAD

**Issue by onemanstartup** [trailblazer/reform-rails#46]
Repository to reproduce error: https://github.com/onemanstartup/reform_rails_simple_for_bug

Main thing is error happens with reform 2.3.0.rc1
```slim
= simple_form_for(@form) do |f|
  .fieldset
    = f.input :name
    = f.button :submit
```

```
undefined method `+' for nil:NilClass

simple_form (3.4.0) lib/simple_form/components/errors.rb:33:in `errors'
simple_form (3.4.0) lib/simple_form/components/errors.rb:13:in `has_errors?'
```

Reform::Contract::Result::Errors when asked attribute returns nil, but ActiveRecord object Product.new.errors[:name] returns empty array. Simple form can't handle nils and throws up.
Even when I remove validation block in form there is still error.

**Comment by onemanstartup** [comment]
@fran-worley I made fix in my fork of reform. I really don't know where it should belong here

**Comment by lastobelus** [comment]
also affects https://github.com/bootstrap-ruby/rails-bootstrap-forms

**Comment by apotonick** [comment]
@onemanstartup Can you point me to your fix so I can have a look, please?

@lastobelus Thanks for confirming! :beers:

**Comment by onemanstartup** [comment]
@apotonick https://github.com/onemanstartup/reform/commit/be0a9fce37ed4fa159b1e2ad16f71fb3e3daa474

**Comment by fran-worley** [comment]
Could we add some of these examples to integration tests in Reform-rails? Then we won't break them again in Reform 3.0!!

**Comment by fran-worley** [comment]
I've added a temporary fix for this on reform branch v2.3.0.rc2 @apotonick can you find a clever way to move this into reform-rails ? I hate having simpleform bits in reform...

**Comment by fran-worley** [comment]
I've also added a patch to get the `f.error_notification` to render correctly. Again, this has had to go in reform so @apotonick will need to get clever before we formally release!

**Comment by apotonick** [comment]
@fran-worley Ok, can you URL me to those changes?

**Comment by fran-worley** [comment]
Sure @apotonick they are here:
https://github.com/trailblazer/reform/commit/44aaeef3f357fd4789e344c12c64645275dca5ab
https://github.com/trailblazer/reform/commit/6c836d9330d7d229a3a92e7731e2ca4c0bd88d67
