### ISSUE TITLE
valid false value throws validation error (blank) in RSpec

### ISSUE THREAD

**Issue by mooreniemi** [trailblazer/reform-rails#47]
```
Note: If you have a question about Reform, would like help using
Reform, want to request a feature, or do anything else other than
submit a bug report, please use the Trailblazer gitter channel.
```

^ The link to the gitter channel 401'd for me. Moving now that Gitlab purchased? Is there a freenode IRC channel I could hit up instead?

### Complete Description of Issue
I have a form with a checkbox. In the form object, this checkbox property is required to be present. (`validates :can_sms, presence: true`) In the underlying model, this column has a nullable Boolean corresponding. 

In RSpec, I'm testing my model's validations without reference to my view code, i.e.

```ruby
  let(:valid_user) { build(:user, can_sms: true) }
  it 'is valid when user and user contact attrs provided' do
    valid_user.user_contact = build(:user_contact)

    form = Ola::StepOne.new(valid_user)
    form.valid?

    expect(form.errors).to be_empty
  end
```

I have to manually set `can_sms: true` above because `can_sms: false` throws a blankness error. (Usually the `User` attributes from the factory_girl factory would set `can_sms: false`.)

When the form is submitted through my view code (a simple .erb template) no such blankness error occurs even when the checkbox is unchecked (so attribute value at that point is `false`). I figure this is my best lead, and when I have some time I intend to try to chase it along so I can give you better steps to reproduce.

### Expected behavior
`false` should be considered a valid value for the form and not throw a validation error.

### Actual behavior
`false` seemingly (my guess?) is coerced to `nil`, and then throws a validation error for blankness.

### System configuration
**Reform version**:
```
    reform (2.2.4)
    reform-rails (0.1.7)
      reform (>= 2.2.0)
```

**Comment by fran-worley** [comment]
@mooreniemi this isn't a reform issue I'm afraid. You can't use presence to validate booleans. See the (rails docs) [http://api.rubyonrails.org/classes/ActiveRecord/Validations/ClassMethods.html#method-i-validates_presence_of]:
"If you want to validate the presence of a boolean field (where the real values are true and false), you will want to use `validates_inclusion_of :field_name, in: [true, false]`."

The gitter channel is still very much live and can be found at https://gitter.im/trailblazer/chat

**Comment by mooreniemi** [comment]
@fran-worley Thanks so much, any idea why this didn't seem to be failing via my view code, but only in RSpec?

**Comment by fran-worley** [comment]
No idea I'm afraid, is your view code actually showing error messages? 
The native rails form helper doesn't render your errors automatically, you either have to add the code yourself or use something like simple form which will render them alongside the inputs.
