### ISSUE TITLE
undefined method `full_messages_for' for Reform::Contract::Result

### ISSUE THREAD

**Issue by Uysim** [trailblazer/reform-rails#68]
When submit form and have validation error

**Comment by fernandes** [comment]
are you pretty sure? this is used in a lot of projects, could you please provide more information?

**Comment by ziyan-junaideen** [comment]
@Uysim I am seeing the same issue... Seems to be an issue with Dry/Reform <-> Simple Form.

**Comment by yogeshjain999** [comment]
Created the fix - https://github.com/trailblazer/reform/pull/539
