### ISSUE TITLE
JSON property with nested data

### ISSUE THREAD

**Issue by jurrick** [trailblazer/reform-rails#7]
If model has JSON field then it is possible to add nested properties for JSON to contract?

Example:

models/station.rb
```
class Station < ActiveRecord::Base
  serialize :settings, JSON
end
```

concepts/station/update.rb
```
class Station::Update < Trailblazer::Operation
  contract do
    property :settings do
      property :briefing
      collection :routes do
        property :name
        ...
      end
      ...
    end
  end
end
```

Then gem raises error message `undefined method 'briefing' for #<Hash:0x007fd47c200aa0>`

What are the ways to solve this problem?

**Comment by apotonick** [comment]
Use the new awesome `JSONB` feature in Reform/Disposable. I will announce it tomorrow.

**Comment by jurrick** [comment]
That's great! I'll wait it!
